name: Dev Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Build development docker image
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
      with:
        push: false
